// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXTskbiv3XyUuKXLJJ62U4PtDOPN9nN8',
    appId: '1:856321449616:web:032c347af8048b18714215',
    messagingSenderId: '856321449616',
    projectId: 'agronew-3fa34',
    authDomain: 'agronew-3fa34.firebaseapp.com',
    storageBucket: 'agronew-3fa34.firebasestorage.app',
    measurementId: 'G-QY2KWS695Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuBwYV8-yZqmXTtT5gw90n-u1hejPkFtw',
    appId: '1:856321449616:android:2dccddfe2bc932a3714215',
    messagingSenderId: '856321449616',
    projectId: 'agronew-3fa34',
    storageBucket: 'agronew-3fa34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrh9mKpGdocClEODgMg1HyPxFxT8Er2CU',
    appId: '1:856321449616:ios:27ce7cbc97c67269714215',
    messagingSenderId: '856321449616',
    projectId: 'agronew-3fa34',
    storageBucket: 'agronew-3fa34.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrh9mKpGdocClEODgMg1HyPxFxT8Er2CU',
    appId: '1:856321449616:ios:27ce7cbc97c67269714215',
    messagingSenderId: '856321449616',
    projectId: 'agronew-3fa34',
    storageBucket: 'agronew-3fa34.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTXTskbiv3XyUuKXLJJ62U4PtDOPN9nN8',
    appId: '1:856321449616:web:bb9241448861ee58714215',
    messagingSenderId: '856321449616',
    projectId: 'agronew-3fa34',
    authDomain: 'agronew-3fa34.firebaseapp.com',
    storageBucket: 'agronew-3fa34.firebasestorage.app',
    measurementId: 'G-DX8059M55R',
  );
}
